#+title: Primer Examen de Programación Lineal
#+author: Licenciatura en Matemáticas Aplicadas, UAEH
#+date: 11 de marzo de 2019
#+language: es

#+options: toc:nil

#+latex_header: \usepackage[margin=2.5cm]{geometry}
#+latex_header: \usepackage[spanish,mexico]{babel}
#+latex_header: \usepackage{tikz}

#+latex_class_options: [twocolumn]

#+latex: \thispagestyle{empty}

*NOMBRE:*
#+latex: \hrulefill

#+latex: \medskip

*INSTRUCCIONES:* Hay 6 preguntas en este examen, debes escoger cinco
de ellas, marcando algún modo claro e inequívoco las preguntas
escogidas. Recuerda explicar sin escatimar en detalles las respuestas
a las preguntas. Tienes 1 hora y 50 minutos para resolverlo.

1. Resuelve el siguiente problema (cualquier método):
   \begin{equation*}
   \begin{aligned}
   \text{Maximizar} \quad & x+2y\\
   \text{sujeto a} \quad &
     \begin{aligned}
      x &\geq  0\\
      y &\geq 0\\
      2x+y &\leq 2
     \end{aligned}
   \end{aligned}
   \end{equation*}
2. Resuelve el siguiente problema (cualquier método):
   \begin{equation*}
    \begin{aligned}
   \text{Maximizar} \quad & x_{1}+2x_{2}\\
   \text{sujeto a} \quad &
     \begin{aligned}
      3x_{1}+4x_{2} &\leq 12\\
      x_{1}-x_{2} &\leq 2\\
      -2x_{1}+x_{2} &\leq 2\\
       x_{1} &\geq 0\\
       x_{2} &\geq 0
     \end{aligned}
   \end{aligned}
   \end{equation*}
3. Resuelve el siguiente problema (cualquier método):
   \begin{equation*}
   \begin{aligned}
   \text{Maximizar} \quad & 4x_{1}+x_{2}+3x_{3}\\
   \text{sujeto a} \quad &
     \begin{aligned}
      x_{1} & \leq 3\\
      x_{2} &\leq 5\\
      x_{3} &\leq 2\\
      x_{1}+x_{2}+2x_{3} &\leq 10\\
      x_{1},x_{2},x_{3} &\geq 0
     \end{aligned}
   \end{aligned}
   \end{equation*}
4. Un gerente está planeando cómo distribuir la producción de tres
   productos entre dos máquinas. Para ser manufacturado cada producto
   requiere cierto tiempo (en horas) en cada una de las máquinas.

   El tiempo requerido está resumido en la siguiente tabla:

   |------------------+---+---|
   | Producto/Máquina | 1 | 2 |
   |------------------+---+---|
   | A                | 1 | 1 |
   | B                | 2 | 1 |
   | C                | 2 | 2 |
   |------------------+---+---|

   La máquina 1 está disponible 40 horas a la semana y la 2 está
   disponible 34 horas a la semana.

   Si la utilidad obtenida al vender los productos A, B y C es de 2, 3
   y 5 pesos por unidad, respectivamente, ¿cuál debe ser la producción
   semanal que maximiza la utilidad? ¿Cuál es la utilidad máxima?
5. Demuestra que el conjunto \(\{(x,y)\mid x\geq 0\}\subseteq
   \mathbb{R}^{2}\) es convexo.
6. Demuestra que la intersección de dos conjuntos convexos es convexo.

* COMMENT Local 

# Local Variables:
# org-confirm-babel-evaluate: nil
# End:
