#+title: Segundo Examen de Programación Lineal
#+author: Licenciatura en Matemáticas Aplicadas, UAEH
#+date: 23 de abril de 2019
#+language: es

#+options: toc:nil

#+latex_header: \usepackage[margin=2.5cm]{geometry}
#+latex_header: \usepackage[spanish,mexico]{babel}
#+latex_header: \usepackage{tikz}

#+latex_class_options: [twocolumn]

#+latex: \thispagestyle{empty}

*NOMBRE:*
#+latex: \hrulefill

#+latex: \medskip

*INSTRUCCIONES:* Hay 6 preguntas en este examen, debes escoger cinco
de ellas, marcando algún modo claro e inequívoco las preguntas
escogidas. Recuerda explicar sin escatimar en detalles las respuestas
a las preguntas. Tienes 1 hora y 50 minutos para resolverlo.

1. Resuelve el siguiente problema:
   \begin{equation*}
   \begin{aligned}
   \text{Maximizar} \quad & 2x+y\\
   \text{sujeto a} \quad &
     \begin{aligned}
      4x+y &\leq 150\\
      2x-3y &\leq -40\\
      x &\geq  0\\
      y &\geq 0
     \end{aligned}
   \end{aligned}
   \end{equation*}
2. Resuelve el siguiente problema:
   \begin{equation*}
    \begin{aligned}
   \text{Maximizar} \quad & 4x_{1}+2x_{2}\\
   \text{sujeto a} \quad &
     \begin{aligned}
      -2x_{1}+x_{2} &\leq 4\\
      x_{1}+2x_{2} &\geq 2\\
       x_{1} &\geq 0\\
       x_{2} &\geq 0
     \end{aligned}
   \end{aligned}
   \end{equation*}
3. Resuelve el siguiente problema:
   \begin{equation*}
    \begin{aligned}
   \text{Maximizar} \quad & 5x_{1}+4x_{2}+3x_{3}\\
   \text{sujeto a} \quad &
     \begin{aligned}
      2x_{1}+3x_{2}+x_{3} &\leq 5\\
      4x_{1}+x_{2}+2x_{3} &\leq 11\\
      3x_{1}+4x_{2}+2x_{3} &\leq 8\\
       x_{1},x_{2},x_{3} &\geq 0
     \end{aligned}
   \end{aligned}
   \end{equation*}
4. Considera el subconjunto convexo \(P\) de \(\mathbb{R}^{2}\)
   determinado por las desigualdades:
   \begin{equation}
      \label{uno}
     \begin{split}
      x+2y &\leq 4\\
       x,y &\geq 0
     \end{split}
   \end{equation}
   - Para cada vértice \(v\) de \(P\), encuentra un vector \(c\) tal
     que el problema de maximizar \(f(x)=c^{T}x\) en la región \(P\)
     encuentre su única solución en \(v\).
   - Encuentra todas las soluciones factibles básicas de la forma
     estándar de un problema de programación lineal determinado
     por \eqref{uno}. 
   - Si \(P'\subseteq \mathbb{R}^{3}\) es la región factible de un
     problema de programación lineal determinado por \eqref{uno}, para
     cada vértice \(v\) de \(P'\), encuentra un vector \(c\) tal que
     el problema de maximizar \(f(x)=c^{T}x\) en la región \(P'\)
     encuentre su única solución en \(v\).
5. Un fabricante produce dos tipos de ropa: \(T_{1}\) y
   \(T_{2}\). Para producir una unidad de \(T_{1}\) se necesitan 4
   unidades de la materia prima \(R1\), 5 unidaes de materia prima
   \(R2\) y una unidad de la materia prima \(R3\). Para producir una
   unidad de \(T_{2}\) los requerimientos, en el mismo orden, son 1, 3
   y 2 unidades, respectivamente. Las cantidades disponibles de \(R1,
   R2\) y \(R3\) son: 56, 105 y 56, respectivamente.

   Si la ganancia de la venta de una unidad de \(T_{1}\) es de $4 y la
   de una unidad de \(T_{2}\) es $5, ¿cuánto se debe producir de
   \(T_{1}\) y \(T_{2}\) para maximizar las ganancias?
6. Una compañía que produce frutas mezcladas tiene en almacén 10,000
   kilos de peras, 12,000 kilos de duraznos y 8,000 kilos de
   cerezas. La compañía produce tres mezclas de frutas, que vende en
   latas de un kilo. La primera combinación contiene la mitad de peras
   y la mitad de duraznos. La segunda combinación contiene cantidades
   iguales de cada fruta. La tercera combinación tiene la mitad de
   duraznos y la mitad de cerezas. Las ganancias por lata vendida por
   cada combinación son de $3, $4 y $5 respectivamente. ¿Cuántas
   latas de cada combinación deberán producirse con el objeto de
   maximizar ganancias? ¿Cuál es la ganancia máxima?


